acproject/ac/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('home/', views.ListHomeView.as_view(), name='home'),
    path('about/', views.TemplateAboutView.as_view(), name='about'),
    path('communication/', views.ListComView.as_view(), name='communication'),
    path('communication/<int:pk>/detail/', views.DetailComView.as_view(), name='communication_detail'),
    path('communication/create/', views.CreateComView.as_view(), name='communication_create'),
    path('communication/<int:com_id>/comment/', views.CreateCommentView.as_view(), name='comment'),
    path('communication/<int:pk>/delete/', views.DeleteComView.as_view(), name='communication_delete'),
    path('communication/<int:pk>/update/', views.UpdateComView.as_view(), name='communication_update'),
    path('official/', views.ListOfficialView.as_view(), name='official'),
    path('communication/<int:pk>/comment-delete/<int:comment_pk>/', views.DeleteCommentView.as_view(), name='comment_delete'),
]

acproject/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import SignupView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
]

acproject/acproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('ac.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acproject/ac/models.py
from django.db import models

from datetime import datetime


CATEGORY = (('everyday', '日常'), ('question', '質問'), ('other', 'その他'))
class Com(models.Model):
    created = models.DateTimeField(default=datetime.now())
    category = models.CharField(
               max_length=100,
               choices = CATEGORY
               )
    image = models.ImageField(null=True, blank=True, upload_to='upload/', default='upload/1896615.jpg')
    title = models.CharField(max_length=100)
    text = models.TextField(max_length=500)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)

    def __str__(self):
        return self.text
    
class Comment(models.Model):
    com = models.ForeignKey(Com, on_delete=models.CASCADE)
    created = models.DateTimeField(default=datetime.now())
    text = models.TextField(max_length=500)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)

    def __str__(self):
        return self.text
    
class News(models.Model):
    created = models.DateTimeField(default=datetime.now())
    text = models.TextField(max_length=100)

class Link(models.Model):
    title = models.CharField(max_length=30)
    image = models.ImageField(upload_to='media/')
    text = models.TextField(max_length=300)

acproject/accounts/models.py
from django.db import models

# Create your models here.

acproject/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',)

acproject/ac/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    ListView,
    TemplateView,
    DetailView,
    CreateView,
    DeleteView,
    UpdateView,
    )
from .models import News, Com, Comment, Link


class ListComView(LoginRequiredMixin, ListView):
    template_name = 'ac/communication.html'
    model = Com

class DetailComView(LoginRequiredMixin, DetailView):
    template_name = 'ac/communication_detail.html'
    model = Com

class CreateComView(LoginRequiredMixin, CreateView):
    template_name = 'ac/communication_create.html'
    model = Com
    fields = ('category', 'title', 'image', 'text')
    success_url = reverse_lazy('communication')

    def form_valid(self, form):
        form.instance.user = self.request.user

        return super().form_valid(form)

class DeleteComView(LoginRequiredMixin, DeleteView):
    template_name = 'ac/communication_delete.html'
    model = Com
    success_url = reverse_lazy('communication')

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)

        if obj.user != self.request.user:
            raise PermissionDenied
        
        return obj

class UpdateComView(LoginRequiredMixin, UpdateView):
    template_name = 'ac/communication_update.html'
    model = Com
    fields = ('category', 'title', 'image', 'text')

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)

        if obj.user != self.request.user:
            raise PermissionDenied
        
        return obj
    
    def get_success_url(self):
        return reverse('communication_detail', kwargs={'pk': self.object.id})

class CreateCommentView(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ('com', 'text')
    template_name = 'ac/comment_create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['com'] = Com.objects.get(pk=self.kwargs['com_id'])
        print(context)

        return context

    def form_valid(self, form):
        form.instance.user = self.request.user

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('communication_detail', kwargs={'pk': self.object.com.id})
    
class ListHomeView(ListView):
    template_name = 'ac/index.html'
    model = News

class TemplateAboutView(TemplateView):
    template_name = 'ac/about.html'

class ListOfficialView(ListView):
    template_name = 'ac/official.html'
    model = Link

class DeleteCommentView(DeleteView):
    template_name = 'ac/comment_delete.html'
    model = Comment

    def get_success_url(self):
        return reverse('communication_detail', kwargs={'pk': self.object.id})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['com'] = Com.objects.get(pk=self.kwargs['com_id'])
        print(context)

        return context

    def form_valid(self, form):
        form.instance.user = self.request.user

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('communication_detail', kwargs={'pk': self.object.com.id})

acproject/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import SignupForm


class SignupView(CreateView):
    model = User
    form_class = SignupForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('home')

acproject/ac/templates/ac/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock %}
{% load static %}
{% block content %}

<div id="contents">

<section>
<h2>About</h2>
<p>このサイトは、あつまれ どうぶつの森のファンが安全に交流することができる場を提供することを目的としています。</p>
</section>

<section id="about">
<h2>当サイトの使い方について</h2>
<h3>Home</h3>
<p>お知らせ欄では、ゲームに関する最新情報などの重要な情報を随時発信しております。<br>
<a href="{% url 'home' %}" target="_blank">お知らせのご確認はこちら</a></p>

<h3>About</h3>
<p>当サイトの使い方についてご説明しております。<br>
ご利用の前によく読んでご確認ください。</p>

<h3>Communication</h3>
<p>自分の島の日常を発信したり、他のユーザーにゲームに関する質問•相談をするなど、自由に使うことができる掲示板です。<br>
ユーザー同士のコミュニケーションの場として、積極的にご活用ください。<br>
<a href="{% url 'communication' %}" target="_blank">掲示板はこちら</a></p>

<h3>Official</h3>
<p>あつまれ どうぶつの森の公式サイトや公式SNS等のリンクを掲載しております。<br>
是非とも公式情報も併せてご確認ください。<br>
<a href="{% url 'official' %}" target="_blank">各種リンクはこちら</a></p>
</section>

</div>

{% endblock content %}

acproject/ac/templates/ac/comment_create.html
{% extends 'base.html' %}

{% block title %}コメント投稿{% endblock %}
{% block h1 %}コメント投稿{% endblock %}

{% load static %}

{% block content %}

    <form method="post" class="p-4 m-4 bg-light border-success rounded form-group">
        {% csrf_token %}
        <label>Text: </label>
        <textarea class="form-control" name="text" rows="3"></textarea>
        <input type="hidden" name='com' value="{{ com.id }}">
        <button type="submit" class="btn btn-success mt-4">投稿する</button>
    </form>

{% endblock %}

acproject/ac/templates/ac/comment_delete.html
{% extends 'base.html' %}

{% block title %}コメント削除{% endblock %}

{% load static %}

{% block content %}

    <form method='post' class="p-4 m-4 bg-light border-success rounded form-group">
        {% csrf_token %}
        <input type="hidden" name='com' value="{{ com.id }}">
        <button type='submit' class="btn btn-success mt-4">コメントを削除する</button>
    </form>

{% endblock %}

acproject/ac/templates/ac/communication.html
{% extends 'base.html' %}
{% block title %}Communication{% endblock %}
{% load static %}
{% block content %}

<div id="contents">

<section>
<h2>Communication</h2>
<a href="{% url 'communication_create' %}"><button type="submit">新規作成</button></a>
{% for item in object_list %}
<div class="list">
<img src="{{ item.image.url }}">
<p>{{ item.created|date:'Y/m/d' }}</p>
<p>(User: {{ item.user.username }})</p>
<p>Category: {{ item.category }}</p>
<h4>Title: {{ item.title }}</h4>
<p>{{ item.text }}</p>
<p><a href="{% url 'communication_detail' item.pk %}" class="btn btn-primary">このスレッドに移動</a></p>
</div>
{% endfor %}
</section>

</div>

{% endblock content %}

acproject/ac/templates/ac/communication_create.html
{% extends 'base.html' %}

{% block title %}スレッド作成{% endblock %}

{% load static %}

{% block content %}

    <form method='post' enctype="multipart/form-data" class="p-4 m-4 bg-light border border-success rounded form-group">{% csrf_token %}
        {{form.as_p}}
        <input type='submit' value='作成する'>
    </form>

{% endblock content %}

acproject/ac/templates/ac/communication_delete.html
{% extends 'base.html' %}

{% block title %}スレッド削除{% endblock %}

{% load static %}

{% block content %}

    <form method='post'>
        {% csrf_token %}
        <button type='submit'>{{ object.title }}を削除する</button>
    </form>


{% endblock %}

acproject/ac/templates/ac/communication_detail.html
{% extends 'base.html' %}
{% block title %}スレッド詳細{% endblock %}
{% load static %}
{% block content %}

<div class="list">
<img src="{{ object.image.url }}">
<p>{{ object.created|date:'Y/m/d' }}</p>
<p>(User: {{ object.user.username }})</p>
<p>Category: {{ object.category }}</p>
<h4>Title: {{ object.title }}</h4>
<p>{{ object.text }}</p>
<a href="{% url 'communication' %}" class="btn btn-primary"><button type="submit">一覧へ</button></a>
<a href="{% url 'comment' object.pk %}" class="btn btn-primary"><button type="submit">コメント</button></a>
<a href="{% url 'communication_update' object.pk %}" class="btn btn-primary"><button type="submit">編集</button></a>
<a href="{% url 'communication_delete' object.pk %}" class="btn btn-primary"><button type="submit">削除</button></a>
</div>

{% for comment in object.comment_set.all %}
<div class="list">
<p>{{ comment.created|date:'Y/m/d' }}</p>
<p>(User: {{ comment.user.username }})</p>
<p>{{ comment.text }}</p>
<a href="{% url 'comment_delete' object.pk comment.id %}" class="btn btn-primary"><button type="submit">削除</button></a>
</div>
{% endfor %}

{% endblock content %}

acproject/ac/templates/ac/communication_update.html
{% extends 'base.html' %}

{% block title %}スレッド編集{% endblock %}

{% load static %}

{% block content %}

    <form method='post' enctype="multipart/form-data" class="p-4 m-4 bg-light border border-success rounded form-group">{% csrf_token %}
        {{ form.as_p }}
        <button type='submit'>編集する</button>
    </form>

{% endblock %}

acproject/ac/templates/ac/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% load static %}
{% block content %}

<div id="contents">

<section id="new">
<h2>お知らせ</h2>
<dl>
{% for item in object_list %}
<dt>{{ item.created|date:'Y/m/d' }}</dt>
<dd>{{ item.text }}</dd>
{% endfor %}
</dl>
</section>

<section>
<h2>サイトのご利用前に必ずお読み下さい</h2>
<h3>利用規約のご案内</h3>
<p><span class="color1">■<strong>荒らし行為は一切禁止です。</strong></span><br>
管理人が見つけ次第、該当ユーザーは退会処分とさせていただきます。</p>
<p><span class="color1">■<strong>個人の特定に繋がる情報は載せないようご注意ください。</strong></span><br>
ゲーム内での交流を楽しみましょう。</p>
<h3>当サイトの詳しい使い方は</h3>
<p><a href="{% url 'about' %}">こちらをご覧下さい。</a></p>
</section>

</div>

{% endblock content %}

acproject/ac/templates/ac/official.html
{% extends 'base.html' %}
{% block title %}Official{% endblock %}
{% load static %}
{% block content %}

<div id="contents">

<section>
<h2>Official</h2>
<table class="ta1">
<caption>各種リンクはこちらから↓</caption>
{% for item in object_list %}
<tr>
<th>{{ item.title }}<br>
<img src="{{ item.image.url }}"></th>
<td><a href="{{ item.text }}">{{ item.text }}</a></td>
</tr>
{% endfor %}
</table>
</section>

</div>

{% endblock content %}

acproject/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block title %}アカウント作成{% endblock %}
{% block h1 %}アカウント作成{% endblock %}
{% load static %}
{% block content %}

<h1>会員登録</h1>
<form method="post" class="p-4 m-4 bg-light border border-success rounded form-group">
    {% csrf_token %}
    <input type="text" name='username' class="form-control my-4" placeholder="ユーザーID">
    <input type="password" name='password1' class="form-control mt-4" placeholder="パスワード">
    <input type="password" name='password2' class="form-control mt-4" placeholder="パスワード確認用">
    <small class="mb-2 d-block text-start">パスワードは8文字以上で設定してください。</small>
    {% if form.errors %}
    <span class="mb-2 small text-danger d-block text-start">利用できないユーザーIDやパスワードの可能性があります。入力内容を再度ご確認ください。</span>
    {% endif %}
    <button type="submit" class="btn btn-success m-2">アカウント作成</button>
</form>

{% endblock %}

acproject/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>{% block title %}{% endblock title %} | あつまれ どうぶつの森ファン向け非公式コミュニティサイト</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="ここにサイト説明を入れます">
<meta name="keywords" content="キーワード１,キーワード２,キーワード３,キーワード４,キーワード５">
<link rel="stylesheet" type="text/css" href="{% static 'ac/css/style.css' %}">
</head>

<body>
<div id="container">
    <header>
        <h1 id="logo"><a href="{% url 'home' %}"><img src="{% static 'ac/images/IMG_0389.jpg' %}" alt="SAMPLE SITE"></a></h1>
        <div class="navbar-nav d-flex flex-row">
            {% if request.user.is_authenticated %}
                <a class="nav-link mx-3" href="{% url 'accounts:logout' %}">ログアウト</a>
            {% else %}
                <a class="nav-link mx-3" href="{% url 'accounts:login' %}">ログイン</a>
                <a class="nav-link mx-3" href="{% url 'accounts:signup' %}">会員登録</a>
            {% endif %}
        </div>
        <aside id="mainimg"><img src="{% static 'ac/images/mainimg.jpg' %}" alt=""></aside>
    </header>
    <nav id="menubar">
        <ul>
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'communication' %}">Communication</a></li>
            <li><a href="{% url 'official' %}">Official</a></li>
        </ul>
    </nav>

{% block content %}{% endblock content %}

<footer>
    <small>Copyright&copy; <a href="{% url 'home' %}">COMMUNICATION SITE</a> All Rights Reserved.</small>
    <span class="pr">《<a href="https://template-party.com/" target="_blank">Web Design:Template-Party</a>》</span>
</footer>
</div>
</body>

</html>